/* Edit this file to update the invitation content, links, and asset paths. */
window.WEDDING_CONFIG = {
  locale: "ar",
  timezone: "Asia/Baghdad",
  couple: {
    groom: { ar: "محمد أديب طويل", en: "Mohamad Adib Tawil" },
    bride: { ar: "رزان بطايحي", en: "Razan Bataihi" },
  },
  event: {
    date: "2026-12-18T19:00:00+03:00",
    dateText: "يوم الجمعة، ١٨ كانون الأول ٢٠٢٦",
    monthText: "كانون الأول 2026",
    weekdayText: "الجمعة",
    dayText: "18",
    timeText: "الساعة السابعة مساءً",
    timezoneLabel: "Asia/Baghdad",
  },
  texts: {
    title: "دعوة زفاف",
    coverSymbol: "&",
    metaDescription: "حضوركم يزيّن فرحتنا. نراكم تحت النجوم.",
    remainingTimeLabel: "الوقت المتبقّي",
    decreaseGuests: "إنقاص العدد",
    increaseGuests: "زيادة العدد",
    whatsappLabel: "واتساب",
    musicLabel: "الموسيقى",
    coverHint: "اضغط لتُضيء النجوم",
    bismillah: "بسم الله الرحمن الرحيم",
    occasion: "حفل زفاف",
    scroll: "مرّر للأسفل",
    verse: "اللّهُمَّ بارِكْ لهُما، وبارِكْ عليهِما، واجمَعْ بينهُما في خير",
    invitationHeading: "بطاقة دعوة",
    invitation: "بقلوبٍ مفعمةٍ بالفرح والسرور، نتشرّف بدعوتكم لمشاركتنا أجمل لحظات حياتنا في حفل زفافنا. حضوركم شرفٌ لنا وبهجةٌ تكتمل بها فرحتنا.",
    groomParentsLabel: "والدا العريس",
    brideParentsLabel: "والدا العروس",
    countdownHeading: "بداية الاحتفال",
    countdownArrived: "اليوم يوم العرس 🎉",
    programHeading: "برنامج الحفل",
    venueHeading: "مكان الحفل",
    notesHeading: "ملاحظات",
    closingNote: "حضوركم يزيّن فرحتنا",
    hashtag: "#دعوة",
    contactLabel: "للاستفسار والتأكيد عبر واتساب",
    contactDisplay: "+963 992 688 759",
    closingFamilies: "عائلة حنّا  &  عائلة عبد العزيز",
    closingThanks: "نراكم تحت النجوم",
    galleryHeading: "بعض ذكرياتنا",
    calendarHeading: "احفظ الموعد ✨",
    calendarCaption: "📲 أضِف الموعد إلى تقويم هاتفك بضغطة",
    googleCalendar: "تقويم جوجل",
    appleCalendar: "تقويم آيفون",
    rsvpHeading: "تأكيد الحضور",
    rsvpSubheading: "يسعدنا تأكيد حضوركم",
    guestNameLabel: "الاسم الكريم",
    guestNamePlaceholder: "اسمك",
    attendanceLabel: "هل ستحضر؟",
    yes: "نعم",
    no: "لا",
    maybe: "ربما",
    companionsLabel: "عدد المرافقين (عدا حضورك — ٠ إن كنت وحدك)",
    messageLabel: "كلمة للعروسين 💌",
    messagePlaceholder: "اكتب تهنئتك للعروسين...",
    submitRsvp: "إرسال التأكيد",
    wishesHeading: "كلمات المهنّئين ✨",
    order: "اطلبه 🎉",
    orderPrompt: "أعجبك قالب «تحت النجوم»؟",
    orderSubtext: "اطلب دعوتك عبر واتساب",
    openInvite: "افتح الدعوة",
    mapLabel: "الموقع على الخريطة",
    countdown: { days: "يوم", hours: "ساعة", minutes: "دقيقة", seconds: "ثانية" },
  },
  family: {
    groom: "نجل السيّد عبد الله حنّا و السيّدة مريم",
    bride: "كريمة السيّد عبد العزيز و السيّدة ليلى",
  },
  venue: {
    name: "قاعة الحمراء للمناسبات",
    address: "بغداد — شارع الكرادة",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Baghdad",
  },
  program: [
    { time: "٧:٠٠ مساءً", title: "استقبال الضيوف" },
    { time: "٨:٠٠ مساءً", title: "مراسم الزفاف" },
    { time: "٩:٠٠ مساءً", title: "العشاء" },
    { time: "١٠:٣٠ مساءً", title: "السهرة والاحتفال" },
  ],
  notes: [
    "يُرجى الحضور قبل الموعد بنصف ساعة",
    "نتشرّف بحضوركم بأبهى حلّة",
    "التصوير مسموح، شاركونا أجمل اللحظات",
    "الدعوة تشمل حاملها والعائلة الكريمة",
  ],
  wishes: [
    { name: "أم محمد", message: "ألف مبروك 🤍 بالرفاه والبنين إن شاء الله، فرحتكم فرحتنا", color: "#e6c878" },
    { name: "سارة", message: "عقبال ما نفرح بيكم بأحلى المناسبات، دعوة بغاية الذوق 😍", color: "#8fa8d8" },
    { name: "حيدر", message: "مبارك الزواج، الله يجعل أيامكم كلها أفراح", color: "#c9a86a" },
    { name: "نور الهدى", message: "بيت جديد عامر بالمحبة إن شاء الله، ألف مبروك", color: "#7d90c9" },
    { name: "أبو علي", message: "الله يبارك لكما ويبارك عليكما ويجمع بينكما في خير", color: "#d8c08a" },
  ],
  links: {
    whatsapp: "https://wa.me/+963992688759",
    googleCalendarBase: "https://calendar.google.com/calendar/render?action=TEMPLATE",
    invitationUrl: "https://mohamad-adib-tawil.github.io/wedding-temp-starlit/",
    fonts: "https://fonts.googleapis.com/css2?family=Aref+Ruqaa:wght@400;700&family=El+Messiri:wght@400;500;600;700&family=Amiri:ital@0;1&family=Tajawal:wght@300;400;500;700&display=swap",
  },
  assets: {
    share: "assets/share-card.svg",
    coverBackground: "",
    gallery: [
      "assets/gallery/1.jpg",
      "assets/gallery/2.jpg",
      "assets/gallery/3.jpg",
      "assets/gallery/4.jpg",
    ],
    musicVideoId: "Hp8WTVqR_0U",
  },
};
